### PR TITLE
One fix, On suggestion

### PR DESCRIPTION
**Pull request by mattn**
* use path/filepath instead of path
* use colorable for windows

### CODE REVIEW

**Comment by nomad-software** [comment]
Looks good but why use `filepath` instead of `file` and why use `stderr` instead of `os.Stderr` etc?

**Comment by nomad-software** [comment]
Thanks

**Comment by mattn** [comment]
path package is not for physical disk. it's provided for http or ftp like path. and windows can't show escape sequence and you write colors into os.Stderr.

**Comment by nomad-software** [comment]
Ah right, thanks.

**Pull request merged**
